In [1]:
import numpy as np

In [3]:
#list 안에 list(2차원배열)
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [6]:
C = np.random.rand(3, 5)
C

array([[0.62497607, 0.01480735, 0.1561599 , 0.8455759 , 0.67614776],
       [0.11727619, 0.30938154, 0.48640966, 0.65078827, 0.36286538],
       [0.99708824, 0.14951891, 0.84201727, 0.56208386, 0.27750683]])

In [10]:
#괄호를 한번 더 써줘야 함
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#행렬에서 원소를 받아오는법

In [12]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [14]:
#파이선은 0부터기 때문에 1행3열은 [0][2]를 써줘야함 
A[0][2]

2

# 요소별 곱하기

In [6]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [0, 1, 2],
    [2, 0, 1],
    [1, 2, 0]
])

In [7]:
A * B

array([[ 0,  2,  6],
       [ 8,  0,  6],
       [ 7, 16,  0]])

# numpy로 행렬 연산하기

In [8]:
import numpy as np

In [9]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

In [10]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [11]:
B

array([[0.40113289, 0.84930458, 0.04047817],
       [0.71952307, 0.93312077, 0.9009092 ],
       [0.39818926, 0.09024453, 0.52673401]])

In [13]:
A + B

array([[ 1.40113289, -0.15069542,  2.04047817],
       [ 3.71952307,  2.93312077,  2.9009092 ],
       [ 4.39818926,  1.09024453,  2.52673401]])

In [14]:
#스칼라곱
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [16]:
#행렬의 곱1
np.dot(A, B)

array([[0.47798833, 0.09667286, 0.19303698],
       [3.43882332, 4.59464431, 2.97672093],
       [3.12043313, 4.51082812, 2.11628989]])

In [17]:
#행렬의 곱2
A @ B

array([[0.47798833, 0.09667286, 0.19303698],
       [3.43882332, 4.59464431, 2.97672093],
       [3.12043313, 4.51082812, 2.11628989]])

In [18]:
A @ B + (A + 2 * B)

array([[2.2802541 , 0.79528201, 2.27399332],
       [7.87786946, 8.46088584, 6.77853934],
       [7.91681164, 5.69131717, 5.16975791]])

# numpy로 전치,단위,역행렬 사용하기

#### 전치행렬 - 행과 열이 서로 바뀐 행렬
#### 단위행렬 - 왼쪽위부터 대각선으로 1, 그외는 0인 행렬(n * n 행렬)
#### 역행렬 - 행렬A와 곱해서 단위행렬이 나오는 행렬

In [20]:
import numpy as np

A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [21]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [24]:
#전치행렬
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [25]:
A.T

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [28]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [31]:
#역행렬이 없어도 최대한 비슷한 효과를 낼 수 있는 역행렬을 리턴해줌
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [32]:
A @ A_inverse

array([[ 1.00000000e+00,  6.66133815e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])