# 6회 기출문제

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e6_p1_1.csv')


df['출동'] = pd.to_datetime(df['출동일자'].astype('str') + df['출동시각'].astype('str').str.zfill(6))
df['신고'] = pd.to_datetime(df['신고일자'].astype('str') + df['신고시각'].astype('str').str.zfill(6))
df['소요시간'] = df['출동'] - df['신고']

df['소요시간'] = df['소요시간'].dt.total_seconds()
print(df.groupby('소방서명').mean()['소요시간'].sort_values(ascending=True).reset_index().iloc[2])

In [111]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e6_p1_2.csv')

city = df[df['학교세부유형'] == '일반중학교'].groupby('시도').size().sort_values(ascending=False).index[1]
normal_seoul = df[(df['학교세부유형'] == '일반중학교') & (df['시도'] == city)]
normal_seoul['value'] = normal_seoul['일반학급_학생수_계'] / normal_seoul['교원수_총계_계']
normal_seoul.sort_values('value', ascending=False).iloc[0]['교원수_총계_계']

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\2126687587.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  normal_seoul['value'] = normal_seoul['일반학급_학생수_계'] / normal_seoul['교원수_총계_계']


33

In [151]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e6_p1_3.csv')

df['총범죄수'] = df.sum(axis=1)
df['년'] = df['범죄분류'].str.split('_').str.get(0)
df.loc[df['범죄분류'].str.split('_').str.get(1).isin(['1월', '2월', '3월']), '분기'] = '1분기'
df.loc[df['범죄분류'].str.split('_').str.get(1).isin(['4월', '5월', '6월']), '분기'] = '2분기'
df.loc[df['범죄분류'].str.split('_').str.get(1).isin(['7월', '8월', '9월']), '분기'] = '3분기'
df.loc[df['범죄분류'].str.split('_').str.get(1).isin(['10월', '11월', '12월']), '분기'] = '4분기'

df.groupby(['년', '분기'], as_index=False).mean().sort_values('총범죄수', ascending=False).iloc[0][['년','분기']]
df[(df['년'] == '2019년') & (df['분기'] == '2분기')]['사기'].max()

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\2412635823.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['총범죄수'] = df.sum(axis=1)


27766

In [213]:
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/ep6_p2_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/ep6_p2_test.csv')

# print(train.info())
# print(train.nunique())
# print(train.isna().sum())
# print(train.columns)

X = train[['Checkup', 'Exercise', 'Heart_Disease',
       'Skin_Cancer', 'Other_Cancer', 'Depression', 'Diabetes', 'Arthritis',
       'Sex', 'Age_Category', 'Height_(cm)', 'Weight_(kg)', 'BMI',
       'Smoking_History', 'Alcohol_Consumption', 'Fruit_Consumption',
       'Green_Vegetables_Consumption', 'FriedPotato_Consumption']]
y = train[['General_Health']]

test_2 = test[['Checkup', 'Exercise', 'Heart_Disease',
       'Skin_Cancer', 'Other_Cancer', 'Depression', 'Diabetes', 'Arthritis',
       'Sex', 'Age_Category', 'Height_(cm)', 'Weight_(kg)', 'BMI',
       'Smoking_History', 'Alcohol_Consumption', 'Fruit_Consumption',
       'Green_Vegetables_Consumption', 'FriedPotato_Consumption']]

X = pd.get_dummies(X)
test_2 = pd.get_dummies(test_2)
test_2 = test_2[X.columns]

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2, random_state=12)
model = RandomForestClassifier(random_state=12)
model.fit(X_train, y_train)

from sklearn.metrics import f1_score, accuracy_score
print(accuracy_score(y_validation, model.predict(X_validation)))
print(f1_score(y_validation, model.predict(X_validation), average='macro'))


pd.DataFrame({'ID' : test['ID'], 'General_Health' : model.predict(test_2)})

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\2135768489.py:32: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


0.5672306322350846
0.5545209106646997


ID General_Health
0     ID_14547      Excellent
1        ID_26      Excellent
2     ID_14103      Excellent
3     ID_10946      Excellent
4      ID_1572      Excellent
...        ...            ...
4808  ID_12991      Excellent
4809  ID_13295           Good
4810   ID_2428           Fair
4811  ID_12719           Good
4812  ID_12691           Good

[4813 rows x 2 columns]

In [219]:
# A 도시의 남성 600명과 여성 550명이 있다. 남성들 중 흡연자 비율은 0.2이며 여성들 중 흡연자 비율은 0.26이다.
# 남성과 여성 간에 흡연 여부에 따른 인구 비율이 다른지 확인하고 싶다. 유의 수준 0.05하 귀무가설에 대해 기각 / 채택 여부와 p-value값을 각각 출력하라

df = pd.DataFrame({'smoke' : [600*0.2, 550*0.26], 'n_smoke' : [600-(600*0.2), 550-(550*0.26)]}, index=['M', 'W'])

from scipy.stats import chi2_contingency
chi2_contingency(df)
display(df)

smoke  n_smoke
M  120.0    480.0
W  143.0    407.0

In [231]:
# age와 Cholesterol을 가지고 weight를 예측하는 선형 회귀 모델을 만들려고한다. age의 회귀 계수를 구하여라

import pandas as pd 
df= pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/28/p7.csv')

import statsmodels.api as sm
X = sm.add_constant(df[['age', 'Cholesterol']])
model = sm.OLS(df['weight'], X)
result = model.fit()

print(result.summary())
result.predict([1, 55, 72.6])

                            OLS Regression Results                            
Dep. Variable:                 weight   R-squared:                       0.044
Model:                            OLS   Adj. R-squared:                  0.038
Method:                 Least Squares   F-statistic:                     7.574
Date:                Fri, 01 Dec 2023   Prob (F-statistic):           0.000608
Time:                        17:50:01   Log-Likelihood:                -1374.9
No. Observations:                 333   AIC:                             2756.
Df Residuals:                     330   BIC:                             2767.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          74.8953      4.455     16.813      

array([78.85771011])

In [216]:
result.pvalues['Cholesterol']

0.00023778081979582106

In [221]:
result.predict([1, 55, 72.6])

array([78.85771011])

In [242]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p1_1_.csv')

df1 = df[(df['20L가격'] != 0) & (df['5L가격'] != 0)]
df1['차이가격'] = df1['20L가격'] - df1['5L가격']
a = df1.groupby('시도명').mean()['차이가격'].max()
round(a, 1)

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\2888797611.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['차이가격'] = df1['20L가격'] - df1['5L가격']


619.0

In [248]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p1_2_.csv')

df['BMI'] = df['weight(kg)'] / (df['height(cm)']/100)**2
len(df[(df['BMI'] >= 25) | (df['BMI'] < 18.5)])


8998

In [270]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p1_3.csv')

out_list = []
in_list = []
for col in df.columns:
    if '전출' in col:
        out_list.append(col)
    elif '전입' in col:
        in_list.append(col)
        
df['순유입인원'] = df[in_list].sum(axis=1) - df[out_list].sum(axis=1)
df.groupby(['년도']).max().sum(axis=0)

지역            중랑구중랑구중랑구중랑구중랑구중랑구중랑구중랑구중랑구중랑구
초등학교_전출_도내                             11879
초등학교_전출_도외                              9142
초등학교_전입_도내                             16810
초등학교_전입_도외                              7943
중학교_전출_도내                               2981
중학교_전출_도외                               2934
중학교_전입_도내                               3532
중학교_전입_도외                               3021
고등학교_전출_도내                              2923
고등학교_전출_도외                              1511
고등학교_전입_도내                              2854
고등학교_전입_도외                              1551
순유입인원                                  13853
dtype: object

In [287]:
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p2_train_.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p2_test_.csv')

X = train.drop(columns=['ID', 'price'])
y = train[['price']]
test_2 = test.drop(columns=['ID'])

X = pd.get_dummies(X)
test_2 = pd.get_dummies(test_2)
test_2[['model_ CLC Class', 'model_ R Class', 'model_180', 'model_200', 'model_230', 'transmission_Other', 'fuelType_Other']] = 0
test_2 = test_2[X.columns]


from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size=0.3, random_state=123)
model = RandomForestRegressor()
model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error
import numpy as np
print(np.sqrt(mean_squared_error(y_train, model.predict(X_train))))
print(np.sqrt(mean_squared_error(y_validation, model.predict(X_validation))))

pd.DataFrame({'ID' : test['ID'], 'price' : model.predict(test_2)})

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\2977772141.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


992.2948605553482
2884.1763017914036


ID     price
0         0   4238.20
1         2  57772.81
2        14  17546.06
3        15  14945.11
4        18  16966.52
...     ...       ...
3291  13096  28633.10
3292  13098  24922.05
3293  13101  23858.61
3294  13109  16921.06
3295  13112  29678.50

[3296 rows x 2 columns]

In [289]:
import pandas as pd 
df= pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p3_1.csv')
df.mean()

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\243926458.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


height    169.937273
dtype: float64

In [303]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e4_p1_1.csv')

df['Temperature'] = df['Temperature'].str.replace('*', '').astype('float')
round(df['Temperature'].quantile(0.75) - df['Temperature'].quantile(0.25), 2)

C:\Users\USER\AppData\Local\Temp\ipykernel_30940\951859961.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Temperature'] = df['Temperature'].str.replace('*', '').astype('float')


27.48

In [308]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e4_p1_2.csv')

# print(df.info())

round(df[((df['Likes']/ df['Comments']) >= 20) & (df['Keyword'] == 'minecraft')]['Views'].mean(), 0)

1789084.0

In [313]:
import pandas as pd 
df= pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e4_p3_1_.csv')
cdf = pd.crosstab(df['학과'], df['성별'])

# import scipy.stats
# dir(scipy.stats)
from scipy.stats import chi2_contingency
chi2_contingency(cdf)

(5.646488667066097,
 0.3421500573497989,
 5,
 array([[159.55772994, 161.44227006],
        [ 84.50097847,  85.49902153],
        [121.28375734, 122.71624266],
        [ 49.20939335,  49.79060665],
        [ 29.32681018,  29.67318982],
        [ 64.12133072,  64.87866928]]))

In [317]:
n = 100
p_hat = 0.6
p = 0.5
alpha = 0.05

(p_hat-p) / np.sqrt((p*(1-p))/n)

1.9999999999999996

In [331]:
from datetime import timedelta

# timedelta 객체 생성 (2일, 3시간, 30분, 15초)
delta = timedelta(days=2, hours=3, minutes=30, seconds=15)

# total_seconds 메서드를 사용하여 총 시간을 초로 변환
total_seconds = delta.total_seconds()

print("총 시간(초):", total_seconds)

총 시간(초): 185415.0
